config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :events
  get 'pages/about', to: 'pages#about', as: :about
  get 'pages/gallery', to: 'pages#gallery', as: :gallery
  get 'pages/members', to: 'pages#members', as: :members
  get 'pages/guidelines', to: 'pages#guidelines', as: :guidelines
  get 'pages/cookie_eu', to: 'pages#cookie_eu', as: :cookie_eu
  get '/profile', to: 'profiles#show', as: :profile
  get '/profile/edit', to: 'profiles#edit', as: :edit_profile
  patch '/profile', to: 'profiles#update', as: :update_profile
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def show
      respond_to do |format|
      format.html { render "show" }
      end  
    end
  
    def edit
      respond_to do |format|
      format.html { render "edit" }
      end  
    end
  
    def update
      if current_user.update(profile_params)
        redirect_to profile_path
      else
        render :edit
      end
    end
  
    private
  
    def profile_params
      params.require(:user).permit(:username, :email, :first_name, :last_name, :date_of_birth, :telephone, :next_of_kin, :previous_injuries, :about_me, :photo)
    end
end  

app/views/profiles/edit.html.erb
<div class="container" style="padding: 50px">
  <div class="row">
    <div class="col-md-12 col-sm-offset-4">
      <%= simple_form_for(current_user, url: update_profile_path) do |f| %>
      <%= f.error_notification %>
      <%= f.input :photo %>
      <%= f.input :photo_cache, as: :hidden %>
      <%= f.input :first_name, placeholder: "First Name" %>
      <%= f.input :last_name, placeholder: "Last Name" %>
      <%= f.input :email, placeholder: "email" %>
      <%= f.input :date_of_birth, placeholder: "DOB" %>
      <%= f.input :next_of_kin, placeholder: "Next of kin" %>
      <%= f.input :telephone, placeholder: "contact number" %>
      <%= f.input :previous_injuries, placeholder: "Any known injuries" %>
      <%= f.input :about_me, placeholder: "Tell us a little about yourself" %>
      <%= f.error :base %>
      <div style="text-align: right;">
      <%= f.submit "Save", class: "btn-treehouse"  %>
      </div>
      <% end %>
       <%= link_to "Back to profile", profile_path, class: "btn-treehouse" %>
    </div>
  </div> 
</div>

app/views/profiles/show.html.erb
<%= content_for :meta_title, "#{current_user.first_name} | #{DEFAULT_META["meta_title"]}" %> 
    <main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1><%= current_user.first_name %></h1>
          <p>
            <a class="btn btn-sm btn-outline-secondary"><%= link_to 'Back to Home page', about_path %></a></p>
            <%= link_to "Edit profile", edit_profile_path, class: "btn-treehouse" %>

        </div>
      </section>
      <div class="album py-5 bg-light" style="padding-top: 20px">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <% if current_user.photo? %>
                <%= cl_image_tag current_user.photo.url(:bright_face) %>
                <% else %>
                <h1>Profile Page</h1>
                <% end %>               
                <div class="card-body">
                <p><strong>First Name:</strong> <%= current_user.first_name %></p>
                <p><strong>Last name:</strong> <%= current_user.last_name %></p>
                <p><strong>Email address:</strong> <%= current_user.email %></p>
                <p><strong>Date of birth:</strong> <%= current_user.date_of_birth %></p>
                <p><strong>Telephone:</strong> <%= current_user.telephone %></p>
                <p><strong>Next of Kin:</strong> <%= current_user.next_of_kin %></p>
                <p><strong>Any previous injuries?</strong> <%= current_user.previous_injuries %></p>
                <p><strong>About me:</strong> <%= current_user.about_me %></p>
                </div>
              </div>
            </div>  
          </div>
        </div>
      </div>
    </main>