config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :events
  get 'pages/about', to: 'pages#about', as: :about
  get 'pages/gallery', to: 'pages#gallery', as: :gallery
  get 'pages/members', to: 'pages#members', as: :members
  get 'pages/guidelines', to: 'pages#guidelines', as: :guidelines
  get 'pages/cookie_eu', to: 'pages#cookie_eu', as: :cookie_eu
  get '/profile', to: 'profiles#show', as: :profile
  get '/profile/edit', to: 'profiles#edit', as: :edit_profile
  patch '/profile', to: 'profiles#update', as: :update_profile
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
end

app/models/event.rb
class Event < ApplicationRecord
    extend SimpleCalendar
    extend FriendlyId
    friendly_id :description, use: :slugged
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show, :index]
  before_action :set_event, only: [:show]
  add_breadcrumb "Event", :events_path

  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @users = User.all
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
    @event = Event.friendly.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    @event = Event.friendly.find(params[:id])
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.friendly.find(params[:id])
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.friendly.find(params[:id])
      add_breadcrumb @event, event_path(@event)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :start_time, :end_time, :location, :description, :type_of_event, :teachers, :performers)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="card" style="height: 150px;">
        <h3><%= event.name %></h3>
            <% if user_signed_in? %>
                <% if current_user.try(:admin?) %>
                <% end %>                 
            <% end %> 
        <h5><%= event.start_time.strftime( '%a %b %e %H:%M ') %></h5>
            <%= link_to 'Show', event %>
            <%= link_to 'Edit', edit_event_path(event) %>
            <%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }%>     
       </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<div class="container" style="padding: 50px;">
  <div class="row">
    <div class="col-md-12 col-sm-offset-4">
      <%= simple_form_for @event do |f| %>
        <%= f.input :name %>
        <%= f.input :teachers %>
        <%= f.input :performers %>
        <%= f.input :type_of_event %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.datetime_select :start_time %>
        <%= f.datetime_select :end_time %>
        <%= f.button :submit, :class => 'btn-treehouse' %>
      <% end %>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<%= render 'form' %>  


  

app/views/events/index.html.erb
<%= content_for :meta_title, "Users | #{DEFAULT_META["meta_title"]}" %>

        <div class="container">
          <h1 class="jumbotron text-centre">Events</h1>
            <a class="btn btn-sm btn-outline-secondary"><%= link_to 'Back to Memebrs page', members_path %></a>          </p>
        </div>

<div class="container">
  <div class="row">
    <% @events.each do |event| %>
    <%= render "event", event: event %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<div style="padding: 50px;">
    <%= link_to 'List all events', events_path, :class => 'btn-treehouse' %>
</div>
<%= render "form" %>

app/views/events/show.html.erb
<div style="padding-top:50px;"> 
<%= link_to 'Back to calendar', members_path, :class => 'btn-treehouse' %>    
</div>    
<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <div class="card" style="height: 450px;">
        <div class="card-category"></div>
          <div class="card-description">
            <h2><%= @event.name %></h2>
            <h4 style="color: whitesmoke;"><%= @event.description %></h4>
            <h4 style="color: whitesmoke;">Teachers: <%= @event.teachers %></h4>
            <h4 style="color: whitesmoke;">Dancers: <%= @event.performers %></h4>
            <h4 style="color: whitesmoke;"><%= @event.location %></h4>
            <h4 style="color: whitesmoke;"><%= @event.start_time.strftime( '%a %b %e %H:%M ') %></h4>
          </div>
      </div>
    </div>
  </div>
</div>
</div>

<div style="padding-top: 50px">
<% if current_user.admin? %>
  <%= link_to 'Edit', edit_event_path(@event), :class => 'btn-treehouse' %>
  <%= link_to 'List all events', events_path, :class => 'btn-treehouse' %>
<% end %>  
</div>