config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :events
  get 'pages/about', to: 'pages#about', as: :about
  get 'pages/gallery', to: 'pages#gallery', as: :gallery
  get 'pages/members', to: 'pages#members', as: :members
  get 'pages/guidelines', to: 'pages#guidelines', as: :guidelines
  get 'pages/cookie_eu', to: 'pages#cookie_eu', as: :cookie_eu
  get '/profile', to: 'profiles#show', as: :profile
  get '/profile/edit', to: 'profiles#edit', as: :edit_profile
  patch '/profile', to: 'profiles#update', as: :update_profile
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
end

app/views/pages/about.html.erb
<%= content_for :meta_title, "About | #{DEFAULT_META["meta_title"]}" %>
<% content_for :title do %>About<% end %>



<div class="container-fluid">
  <div class="row">
    <div class="col-12">
      <%= video_tag("https://res.cloudinary.com/minerva-ballet/video/upload/v1550775986/MINERVA_BALLET_PROMO..mp4", 
      :height => 200, :width => 350, :controls => true, :fallback_content => "Your browser does not support HTML5 video tags" ) %>
      
      <div class="about-page">
<p>Minerva Ballet is a new London based amateur adult ballet company with a fresh, professional approach. At Minerva Ballet we aim to bring our dancers from the studio to the stage.  As adult dance students, you will have been taught ballet technique, you may even have become accustomed to a particular method or teacher.  What none of this prepares you for is performance.</p>

<p>All of our teachers have worked internationally as ballet dancers, and are keen to teach amateurs the art of performance.  From the basics of stagecraft, to how to communicate with an audience, and how to deal with mishaps on stage, our teachers’ combined experience will help our dancers step away from the barre and become performers.</p>
<p>If you would like to be involved, please
<%= mail_to "info@minervaballet.com" do %>
  <strong>get in touch.</strong>
<% end %> 
</p>
<h2>Our Teachers</h2>
<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316778/patrick.jpg", :height => 200, :width => 300, :crop => "pad")%>
<h3>Patrick Hood, Artistic Director.</h3>
<p class="about-page">Patrick is our artistic director and has decades of experience in the professional dance world.  Patrick was a principal dancer with the Vienna Festival Ballet, among others, and is an inexhaustible supply of information and wisdom on partnering and artistry.  

After retiring from professional ballet, Patrick has pursued interests inside and outside the dance world.  He continues to dance professionally. 
</p>
<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316778/Sheila.jpg", :width => 300, :crop => "pad")%>
<h3>Sheila Styles, Ballet Mistress</h3>
<p>Sheila has an international reputation as a dancer, teacher and choreographer.  Her professional ballet journey started at the Royal Ballet School, and this grounding saw her perform as a principal dancer for several companies internationally.  Sheila brings with her a wealth of knowledge and experience having worked with some of the most iconic names in ballet.  As well as being an incomparable technician, she is an inspirational artist and communicator.  As a choreographer, she is intelligent and innovative.  We are delighted that Sheila will be joining us. </p>


<h2>Guest Teachers</h2>
<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316778/teach2.jpg", :width => 300, :crop => "pad")%>


<h3>Inga George</h3>
<p>Inga George graduated with distinction from the V. Chabukiani Ballet
School in Tbilisi, Georgia, and joined the National State Opera and Ballet
Theatre of Georgia. Inga rose to the rank of Prima Ballerina. Later in her
career, she was appointed Assistant Artistic Director of the V. Chabukiani
Ballet School. She now teaches vocational and adult students in London.</p>

<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316778/teach1.jpg", :width => 300, :crop => "pad")%>
<h3>Alyona Solovkova </h3>
<p>Alyona Solovkova began her training in Russia, where she underwent 7 years of professional training.
She was awarded a full scholarship to attend Central Ballet School, London and graduated in 2004.
 On Graduation, Alyona performed as a soloist at both the Constanta and Iasi Opera Houses, Romania. 
 She also performed with the Kirov Ballet at the Royal Opera House.  
She now teaches vocational, pre-vocational and adult students in London.</p>

<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316778/dance.jpg", :width => 300, :crop => "pad")%>

<h3>Viaceslav Baltaga</h3>
<p>Viaceslav Baltaga graduated from the renowned Kiev State Ballet School in 1994 where, as a student, he won several International competitions. He became a soloist three years later and a principal with the Constanta Opera House, Romania, where he remained until 2005. He has danced most of the iconic male roles.  
Viaceslav now teaches vocational and prevocational students, as well as coaching students for auditions and international competitions. </p>

<h2>Current Repertoire</h2>
<p>This season we are working on a triple bill.</p>



<p><%= link_to "https://www.youtube.com/watch?v=LBJNc3h7Hp8", target: :_blank do %>
  <strong>Les Sylphides</strong><% end %>  is an iconic, non-narrative ballet, choreographed by Mikhail Fokine.  Orchestrated by Glazunov, the piano music of Chopin sets the scene of ethereal beauty and dreams.  Woodland sylphs dance for a young man, the poet, in the moonlight.   This is a stylised and technically demanding ballet, requiring unfaltering corps de ballet discipline, clean lines, and fluid port de bras.  

The “romantic rêverie” we recognise as Les Sylphides was first performed by Diaghilev’s Ballets Russes in the Théâtre du Châtelet in June 1909.  Its soloists were Tamara Karsavina, Vaslav Nijinsky and Anna Pavlova.  The long romantic tutu was designed by Léon Bakst, and inspired by a lithograph of Marie Taglioni as a sylph.</p>
<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316778/dance1.jpg", :width => 300, :crop => "pad")%>

<p> Original set, 1909</p>
<%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1550316777/tamara.jpg", :width => 150)%>
<h3>Tamara Karsavina in Les Sylphides</h3>
<p>This work will challenge our dancers and delight our audience, lulling the latter into a beautiful dream.  It will open our triple bill, and serve as a contrast to the next work, Polovtsian Dances.</p>


<p><%= link_to "https://www.youtube.com/watch?v=xsnf2vski5c", target: :_blank do %>
  <strong>Polovtsian dances</strong><% end %> consists of a series dances from the second act of Borodin’s historical epic opera, Prince Igor.  It is set in the encampment of Khan Kontchak, leader of twelfth century Polovtsian army.  Prince Igor and his son have been captured, and are entertained by the warriors dancing.  
This work demonstrates the versatility, innovation and musicality of Fokine’s choreography.  The Borodin score is as beautiful as it is primal, and conjures up the energy, flamboyance and turbulence of the twelfth century central Asia. 

For our dancers, this will provide a further challenge, and have enlisted the help of a Russian character teaching to ensure a holistic and faithful approach to this work.</p>

<p>Our final piece is <%= link_to "https://youtu.be/QZ8Ypptc4h0", target: :_blank do %>
  <strong>“Lights. Camera. Action”</strong><% end %>, a lighthearted and humorous look at Hollywood’s golden era. The Gershwin score introduces many characters from the silver screen, 
ending with a chorus line and awards ceremony.</p>

<p style="font-weight: bolder">We are always keen to recruit dancers who wish to perform. If you would like to join us,
 <%= mail_to "info@minervaballet.com" do %>
  <strong>get in touch.</strong>. <% end %> 
</p>
</div>
    </div>
  </div>
</div>




<%= render 'layouts/footer' %>

app/views/pages/cookie_eu.html.haml
%h2 COOKIES

%p Cookies are small text files which are downloaded to your computer, tablet or mobile phone when you visit a website or application. The website or application may retrieve these cookies from your web browser (eg Internet Explorer, Mozilla Firefox or Google Chrome) each time you visit, so they can recognise you, remember your preferences and provide you with a more secure online experience.

%p Generally, cookies are very useful and are a common method used by almost every website you visit because they help to make your online experience as smooth as possible. For security reasons, many websites will not function at all without the use of cookies (or other similar technologies, such as "web beacons" or "tags").

%p Cookies generally do not hold any information to identify an individual person, but are instead used to identify a browser on an individual machine.

%p If you prefer, you can restrict, block or delete cookies by changing your browser settings but that may mean that the website won't work properly

%p For more information about cookies and their impact on you and your browsing visit #{link_to 'http://www.aboutcookies.org', 'www.aboutcookies.org'}.


%h2 TYPES OF COOKIES

%h3 Necessary cookies

%p These cookies are essential in helping you to make use of the features and services we offer on the Minerva website. Without these cookies, the services you want to use cannot be provided. These cookies do not gather information about you that could be used to identify you, and they do not monitor or remember where you have been on the internet.

%h3 Functional cookies

%p These cookies allow us to provide you with a better online experience when you use our website. They do not gather or store any information which would allow us to identify you personally.

%h3 Performance cookies

%p Performance cookies help us to understand how our customers use our site, so we can keep our products and services relevant, easy to use and up to date. For example, we can see which products and services are most popular, identify when and where errors occur, and test different versions of a page in order to provide an improved online experience.

%p Sometimes, the services we use to collect this information may be operated by other companies on our behalf. They may use similar technologies to cookies, known as "web beacons" or "tags". These are anonymous and, as they are only used for statistical purposes, they do not contain or collect any information that identifies you.

%h3 Targeting cookies

%p We have relationships with carefully selected and monitored suppliers (third parties) who may also set cookies during your visit. The purpose of these cookies is "behavioural advertising" (also known as "behavioural targeting" or "remarketing"), which is a means of showing you relevant products and services based on what you appear to be interested in. Although these cookies can track your visits around the web they don't know who you are. Without these cookies, online advertisements you encounter will be less relevant to you and your interests.


%h2 MANAGING COOKIES

%p Most internet browsers allow you to erase cookies from your computer hard drive, block all cookies (or just third-party cookies) or warn you before a cookie is stored on your device.

%p Please note, if you choose to block all cookies, our site will not function as intended and you will not be able to use or access many of the services we provide. If you have blocked all cookies and wish to make full use of the features and services we offer, you will need to enable your cookies. You can do this in your browser (see below).

%p Rather than blocking all cookies, you can choose to only block third-party cookies which will still allow our website to function as intended.

%h3 How to manage cookies on your PC

%p To enable cookies on our website, follow the steps below.

%h4 Google Chrome

%ol
  %li Click "Tools" at the top of your browser and select "Settings".
  %li Click "Show advanced settings", scroll down to the section "Privacy" and click "Content Settings."
  %li Select "Allow local data to be set". To only acept first-party cookies, check the box next to "Block all third-party cookies without exception"

%h4 Microsoft Internet Explorer 6.0, 7.0, 8.0, 9.0

%ol
  %li Click "Tools" at the top of your browser and select "Internet Options", then click the "Privacy" tab.
  %li Check that the level of your privacy is set to Medium or lower, which will allow the use of cookies in your browser.
  %li If set above medium level it will prevent the use of cookies.

%h4 Mozilla Firefox

%ol
  %li Click "Tools" at the top of your browser and select "Options".
  %li Then select the "Privacy" icon.
  %li Click the "Cookies" and select "Allow pages to create a cookie."

%h4 Safari

%ol
  %li Click the gear icon at the top of your browser and select "Settings".
  %li Click the "Privacy" tab, then select the option "Disable the use of cookies by third parties and advertising cookies."
  %li Click "Save".

%h3 How to manage cookies on your Mac

%p To enable cookies on our website, follow the steps below.

%h4 Microsoft Internet Explorer 5.0 on OSX

%ol
  %li Click on "Explorer" at the top of your browser and select "Settings".
  %li Scroll down to the "Cookies" section in the "Received Files".
  %li Select "Do not ask."

%h4 Safari on OSX

%ol
  %li Click "Safari" on the top of your browser and select "Settings".
  %li Click the "Privacy" and then "Enable cookies."
  %li Select "only the pages you have visited."

%h4 Mozilla and Netscape on OSX

%ol
  %li Click "Mozilla" or "Netscape" at the top of your browser and select "Settings".
  %li Scroll down to the "Cookies" under "Privacy & Security".
  %li Select "Allow cookies only to the original site."

%h4 Opera

%ol
  %li Click "Menu" on the top of your browser and select "Settings".
  %li Then select "Options" tab and the "Advanced".
  %li Select "Enable cookies."

app/views/pages/gallery.html.erb
<%= content_for :meta_title, "Gallery | #{DEFAULT_META["meta_title"]}" %>
    <main role="main">
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Minerva Gallery</h1>
          <p class="lead text-muted">Previous perfomances</p>
          <p>
            <a class="btn btn-sm btn-outline-secondary"><%= link_to 'Back to Home page', about_path %></a>          </p>
        </div>
      </section>
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            <div class="col-sm-4">
              <div class="card mb-4 box-shadow">
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1570185193/16.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1570185193/8a.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1570185193/12.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1574778461/image2.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1574778461/image3.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1574778461/image1.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1574778461/image5.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1574778461/image4.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/ballet_shoes_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/Minerva_4_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/Minerva_5_Output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/Minerva_7_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/Minerva_6_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/Minerva_3_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965758/Minerva_Eleanora_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965757/Tania_output.jpg", :width => 300, :crop => "pad")%>
                <%= cl_image_tag("https://res.cloudinary.com/minerva-ballet/image/upload/v1579965730/Sarah_and_Patrick_output.jpg", :width => 300, :crop => "pad")%>

              </div>
            </div>

app/views/pages/guidelines.html.erb
<div class='about-page'><h1>Minerva ballet</h1>
<h2>Information for Dancers</h2>

<h3>1. Personnel</h3> 
<p>1.1 The company director and founder is Patrick Hood<br>
1.2 Patrick Hood is Artistic Director<br>
1.3 Sheila Styles is ballet mistress and coach<br>
1.4 Others will be appointed for specialist coaching at the discretion of the Artistic Director</p>

<h3>2. Ethos of the company</h3>
<p>2.1 Minerva Ballet is an adult ballet company seeking to present professional performances<br>
2.2 A professional attitude is expected by all involved.  This includes good time keeping, good attendance, and maintenance of good technique through attending appropriate, approved classes outside rehearsal time.  Women must attend at least one pointe class per week</p>

<h3>3. Repertoire and casting</h3>
<p>3.1 Casting and repertoire decisions are the sole responsibility of the Artistic Director. The Programme will be determined for the next performance and casting will be based on ability and suitability.  If dancers wish to discuss dancing a particular role, they may do so, but inclusion in any programme is not guaranteed.   This is to ensure that artistic integrity and standards are maintained.<br>
3.2 Any proposals for repertoire will be approved by the Artistic Director to ensure suitability and feasibility.<br>
3.3 Casting is dependent on good attendance and performance.  If the Artistic Director feels that a dancer is underperforming, they will be recast.</p> 

<h3>4. Principal Roles</h3>
<p>4.1 Casting in a principal role is at the discretion of the Artistic Director.  No petitions for roles will be accepted. <br>
4.2 Principals will be required to undertake private coaching sessions with the Artistic director or a nominated coach.<br>
4.3 Regular attendance at approved classes will be required for all those cast in a principal role.</p>

<h3>5. Conduct during rehearsals</h3>
<p>5.1 Courtesy should be shown to all with noise levels kept to a minimum.<br>
5.2 Use of mobile phones should be kept to an absolute minimum.<br>
5.3 Videos should be used for critique, not for learning repertoire, and will be permitted on this basis.<br>
5.4 All dancers should get into the habit of bringing a notebook to rehearsals and recording the repertoire which has been covered.<br>
5.5 Timekeeping is of the utmost importance.</p>

</div>

app/views/pages/members.html.erb
<% content_for :title do %>Members<% end %>

<div class="container-fluid">
  <div class="row">
    <div class="col-12">


<%= content_for :meta_title, "Members | #{DEFAULT_META["meta_title"]}" %>
<div class='about-page'><p>Welcome to our members’ area.  You will receive an email acknowledging your sign-up.  
Here, you will find rehearsal schedules and cast sheets, as well as documents posted by our artistic director.</p>  
<p>Please read our <%= link_to "guidelines for dancers", guidelines_path, target: :_blank %>
</div>

<div class='about-page'><p>
<%= link_to('A video of our last performance which included The Four Seasons.',"https://www.youtube.com/watch?v=hQ3mNHTtGm0", target: :_blank) %></p>
</div>

<div style='padding-bottom: 50px;'>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <%= link_to 'New Event', new_event_path, class: 'btn-treehouse'%>
     <%= link_to 'List all events', events_path, :class => 'btn-treehouse' %>
  <% end %>
<% end %>
</div>

<div>
<%= month_calendar events: @events do |date, events| %>
  <%= date.to_formatted_s(:short) %>
  <% events.each do |event| %>
    <div class='cal-card'> 
      <div class="mobile-hide">
        <%= event.name  %><br>
        <%= event.start_time.strftime('%H:%M')%> - <%= event.end_time.strftime('%H:%M')  %>
      </div>
      <% if current_user %>
          <%= link_to "", event_path(event), class: "card-link"%>
      <% end %>
    </div>
  <% end %>
<% end %>
</div>

    </div>
  </div>
</div>