config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"
  match "/404", to: "errors#not_found", via: :all
  match "/422", to: "errors#unacceptable", via: :all
  match "/500", to: "errors#internal_server_error", via: :all
  resources :events
  get 'pages/about', to: 'pages#about', as: :about
  get 'pages/gallery', to: 'pages#gallery', as: :gallery
  get 'pages/members', to: 'pages#members', as: :members
  get 'pages/guidelines', to: 'pages#guidelines', as: :guidelines
  get 'pages/cookie_eu', to: 'pages#cookie_eu', as: :cookie_eu
  get '/profile', to: 'profiles#show', as: :profile
  get '/profile/edit', to: 'profiles#edit', as: :edit_profile
  patch '/profile', to: 'profiles#update', as: :update_profile
  namespace :admin do
    resources :users
    root to: "users#index"
  end
  root to: 'visitors#index'
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users
end

app/views/layouts/_footer.html.erb
  <footer>
  <div class="footer" style="background-image: linear-gradient(55deg, rgba(100,150,150,0.9) 10%, rgba(102,151,150,0.3) 65%), url('https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiS4dCT7uLfAhVE6RoKHQtWCA0QjRx6BAgBEAU&url=https%3A%2F%2Fwww.sfballet.org%2Fabout%2Frentals%2Fstudio-rental&psig=AOvVaw3y09I0nCneKb-Rd5U6Z_Ys&ust=1547197310539567');">
      <div class="row">
        <p>Copyright &copy; Minerva Ballet 2019</p>
        <%= link_to('Powered by Fouldsy', 'http://www.deanfoulds.xyz/') %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Profile', profile_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Members', users_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="avatar-small"><%= link_to image_tag('min.png'), root_path %></li>
    
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Gallery', page_path('gallery') %></li>
<% if user_signed_in? %>
  <li><%= link_to 'Members area', members_path  %></li>
  <li><%= link_to 'Guidelines', guidelines_path, target: :_blank %></li>
<% else %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Mukta" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <%= favicon_link_tag asset_path('min.png'), :rel => 'icon', :type => "image/x-icon" %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> <%= meta_title %> </title>

<meta name="description" content="Minerva Ballet is a new London based amateur adult ballet company with a fresh, professional approach. At Minerva Ballet we aim to bring our dancers from the studio to the stage. As adult dance students, you will have been taught ballet technique, you may even have become accustomed to a particular method or teacher. What none of this prepares you for is performance.">

<meta property="og:title" content="#{meta_title}">
<meta property="og:type" content="website">
<meta property="og:url" content="#{request.original_url}">
<meta property="og:image" content="#{meta_image}">
<meta property="og:description" content="#{meta_description}">
<meta property="og:site_name" content="#{meta_title}">


<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="#{DEFAULT_META['twitter_account']}">
<meta name="twitter:title" content="#{meta_title}">
<meta name="twitter:description" content="#{meta_description}">
<meta name="twitter:creator" content="#{DEFAULT_META['twitter_account']}">
<meta name="twitter:image:src" content="#{meta_image}">


    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'true' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'true' %>
    <%= cloudinary_js_config %>
    <%= csrf_meta_tags %>
    <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-132051209-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-132051209-1');
</script>

  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %> 
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
   
  </body>
</html>